import re
from playwright.sync_api import Playwright, sync_playwright, expect


def test_run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.zara.com/ua/")
    page.get_by_role("button", name="Дозволити всі файли cookie").click()
    page.get_by_role("button", name="ЖІНКИ").click()
    page.get_by_role("link", name="сукні").click()
    page.get_by_role("button", name="КОЛІР").click()
    page.locator("label").filter(has_text="ANIMAL PRINT").locator("span").first.click()
    page.get_by_role("button", name="КОЛЕКЦІЯ").click()
    page.get_by_text("БІЛИЗНА").click()
    page.get_by_text("CRLR").click()
    page.get_by_role("link", name="ТЮЛЕВА СУКНЯ-СЛІП З ТВАРИННИМ ПРИНТОМ - Леопардовий Zara").click()
    page.get_by_role("option", name="S").click()
    page.get_by_label("Додати ТЮЛЕВА СУКНЯ-СЛІП З ТВАРИННИМ ПРИНТОМ").click()
    page.get_by_label("Закрити").click()
    page.get_by_label("Відкрити меню").click()
    page.get_by_role("button", name="чоловіки").first.click()
    page.locator("a").filter(has_text="штани").nth(1).click()
    page.get_by_role("button", name="КОЛІР").click()
    page.locator("label").filter(has_text="Коричневий").locator("span").first.click()
    page.get_by_role("link", name="Чіно", exact=True).click()
    page.get_by_role("link", name="ШИРОКІ ШТАНИ-ЧІНО - бежево-коричневий Zara").click()
    page.get_by_role("option", name="40").click()
    page.get_by_label("Додати ШИРОКІ ШТАНИ-ЧІНО").click()
    page.get_by_label("Закрити").click()
    page.get_by_label("Відкрити меню").click()
    page.get_by_role("button", name="діти").first.click()
    page.get_by_role("button", name="–6 місяців").click()
    page.get_by_role("link", name="/// новинки").click()
    page.get_by_role("button", name="КОЛІР").click()
    page.locator("label").filter(has_text="Червоний").locator("span").first.click()
    page.get_by_role("button", name="ТИП ТОВАРУ").click()
    page.get_by_role("button", name="ТИП ТОВАРУ").click()
    page.get_by_role("link", name="ТРИКОТАЖНИЙ КОМБІНЕЗОН ОБОРОТНОГО ПЕРЕПЛЕТЕННЯ - Червонуватий Zara").click()
    page.goto("https://www.zara.com/ua/uk/kids-newborn-new-l6843.html?v1=2434926")
    page.get_by_role("button", name="КОЛІР (1)").click()
    page.locator("label").filter(has_text="З принтом").locator("span").first.click()
    page.locator("label").filter(has_text="Зелений").locator("span").first.click()
    page.get_by_role("link", name="ОДНОТОННИЙ КРЕПОВИЙ ЧЕПЧИК - Морський зелений Zara").click()
    page.get_by_role("option", name="-3 місяці(-в) (38 cm)").click()
    page.get_by_label("Додати ОДНОТОННИЙ КРЕПОВИЙ ЧЕПЧИК").click()
    page.get_by_label("Закрити").click()
    page.get_by_label("Товари в кошику: 3").click()
    page.get_by_label("Додати ще одну одиницю товару - ОДНОТОННИЙ КРЕПОВИЙ ЧЕПЧИК").click()
    page.get_by_label("Додати ще одну одиницю товару - ОДНОТОННИЙ КРЕПОВИЙ ЧЕПЧИК").click()
    page.get_by_role("button", name="ПРОДОВЖИТИ").click()
    page.get_by_role("button", name="Продовжити без реєстрації").click()
    page.locator("#main div").filter(has_text="Ім'яПрізвищеАдресаДодаткова інформаціяПоштовий індекс--КиївХарківська областьОде").nth(2).click()
    page.get_by_label("Ім'я").click()
    page.get_by_label("Ім'я").fill("")
    page.get_by_label("Ім'я").press("CapsLock")
    page.get_by_label("Ім'я").fill("Катерина")
    page.get_by_label("Ім'я").press("Tab")
    page.get_by_label("Прізвище").fill("Іванченко")
    page.get_by_label("Адреса").click()
    page.get_by_label("Адреса").fill("Ткаченка 5")
    page.get_by_label("Поштовий індекс").click()
    page.get_by_label("Поштовий індекс").fill("39605")
    page.get_by_label("Область").select_option("UAPL")
    page.get_by_label("Район").select_option("UAPLD06")
    page.get_by_label("Місто").select_option("UAPLD06C74")
    page.get_by_label("Електронна пошта").click()
    page.get_by_label("Електронна пошта").press("CapsLock")
    page.get_by_label("Електронна пошта").fill("iradzerj@gmail.com")
    page.get_by_label("Телефон").click()
    page.get_by_label("Телефон").fill("677676859")
    page.get_by_role("button", name="ПРОДОВЖИТИ").click()
    page.get_by_role("link", name="у пункті видачі у пункті видачі").click()
    page.get_by_placeholder(" ").click()
    page.get_by_placeholder(" ").fill("")
    page.get_by_placeholder(" ").press("CapsLock")
    page.get_by_placeholder(" ").fill("кременчук")
    page.get_by_role("button", name="Пошук").click()
    page.locator("label").filter(has_text=re.compile(r"^КременчукВідділення №2$")).click()
    page.get_by_role("button", name="Зберегти").click()
    page.get_by_role("button", name="ПРОДОВЖИТИ").click()
    page.get_by_role("img", name="VISA").click()
    page.locator("div").filter(has_text=re.compile(r"^VISA$")).click()
    page.get_by_role("button", name="ПРОДОВЖИТИ").click()
    page.get_by_role("link", name="Перейти на головну сторінку").click()
    page.get_by_role("link", name="ДОПОМОГА").click()
    page.get_by_role("button", name="ЯК ЗДІЙСНИТИ ПОВЕРНЕННЯ").click()
    page.get_by_role("link", name="Показати всі теми довідника").click()
    page.get_by_role("link", name="ЯК ЗДІЙСНИТИ ПОВЕРНЕННЯ").click()
    page.get_by_role("button", name="ЯК ПІДГОТУВАТИ ПАКУНОК ІЗ ПОВЕРНЕННЯМ?").click()
    page.get_by_role("button", name="Я ПОДАВ(-ЛА) ЗАПИТ НА ЗАБІР ЗАМОВЛЕННЯ, АЛЕ ЙОГО НЕ БУЛО ВИКОНАНО. ЩО Я МОЖУ ЗРО").click()
    page.get_by_role("button", name="ОСОБЛИВІ УМОВИ ПОВЕРНЕННЯ").click()
    page.get_by_text("Аксесуари для волосся").click()
    page.get_by_label("Відкрити меню").click()
    page.get_by_role("link", name="магазини").nth(2).click()
    page.get_by_placeholder(" ").click()
    page.get_by_placeholder(" ").fill("київ")
    page.get_by_placeholder(" ").press("Enter")

    # ---------------------
    context.close()
    browser.close()



